gyuheon0h/design-proj

client/package.json
client/src/pages/Auth.tsx

Basic login UI

---

client/src/App.tsx
client/src/pages/Login.tsx
client/src/pages/Register.tsx

not super styled yet
tested with passwords not matching
all fields required
will alert user if something is missing

Signup page

---

server/src/app.ts
server/src/db_models/UserModel.ts
server/src/routes/api.ts
server/src/routes/auth/register.ts

```
curl -X POST http://localhost:5001/api/register \
-H "Content-Type: application/json" \
-d '{
"username": "john_doe",
"email": "john@example.com",
"passwordHash": "hashed_password_from_client"
}'
{"message":"User registered successfully.","user":{"id":"266feab0-b716-464e-a6aa-9ba82ff69d01","username":"john_doe","createdat":"2025-01-30T22:40:47.171Z","deletedat":null,"passwordhash":"hashed_password_from_client","email":"john@example.com"}}%    
curl -X POST http://localhost:5001/api/register \
-H "Content-Type: application/json" \
-d '{
"username": "john_doe",
"email": "john@example.com",
"passwordHash": "hashed_password_from_client"
}'
{"message":"Username already taken."}% …
```

Register backend api done

---

client/src/App.tsx
client/src/components/Drawer.tsx
client/src/components/FileContainer.tsx
client/src/components/Filter.tsx
client/src/components/FolderContainer.tsx
client/src/components/SearchBar.tsx
client/src/pages/Favorites.tsx
client/src/pages/Folder.tsx
client/src/pages/Home.tsx
client/src/pages/Login.tsx
client/src/pages/Shared.tsx
client/src/pages/Trash.tsx

added 2 pages (favorites, trash), search bar, and filters

---

client/src/Styles.tsx
client/src/components/Drawer.tsx
client/src/components/Folder.tsx
client/src/components/SearchBar.tsx
client/src/index.css
client/src/index.tsx

beginning styling changes, we can def still change the font

beginning styling changes

---

client/src/components/FileContainer.tsx
client/src/pages/Home.tsx
client/src/pages/UploadDialog.tsx
server/src/routes/auth/login.ts

- create file button
- opens up a modal

Add file button

---

client/src/components/File.tsx
client/src/components/FileContainer.tsx
client/src/pages/Home.tsx
server/src/routes/files/files.ts

We can now soft delete files. This still doesnt remove from GCS, but that is the next task after we figure out how we can manage soft deletions
https://github.com/user-attachments/assets/c9326757-304e-426f-8bbc-731965837b25

Soft delete files

---

client/src/components/Folder.tsx

frontend favorites button

---

client/src/components/Folder.tsx
client/src/components/FolderContainer.tsx
server/src/routes/folders/folders.ts

soft delete folder

---

server/src/db_models/PermissionModel.ts

Permission Model

---

server/src/routes/files/files.ts
server/src/routes/folders/folders.ts

- sorted in descending order
- should no longer change orders when u favorite

sorting files and folders in backend based on createdAt

---

client/src/components/Filter.tsx
client/src/components/SearchBar.tsx

https://github.com/user-attachments/assets/f85ce5aa-e29d-4482-a899-e4f57a180364

Reset for filters

---

client/src/App.tsx
client/src/pages/FavoritesPage.tsx
client/src/pages/HomePage.tsx
client/src/pages/SharedPage.tsx
client/src/pages/TrashPage.tsx

removed the redudant search query param from App.tsx layer and all the duplicate page props

removed redudant search query

---

client/src/components/File.tsx

File icon rendering done by ethan

File icon rendering

---

client/src/components/TextEditor.tsx
server/src/websocket.ts

gonna roll this back but need preview deploy

Edit concurrency slight improvement

---

client/src/pages/RegisterPage.tsx

email validations

---

client/src/components/CreateButton.tsx
client/src/components/Drawer.tsx
client/src/components/File.tsx
client/src/components/Page.tsx
client/src/components/StorageAnalytics.tsx
client/src/context/StorageContext.tsx
client/src/context/StorageContxt.tsx
client/src/index.tsx
client/src/interfaces/File.ts
server/src/db_models/FileModel.ts
server/src/routes/files/files.ts
server/src/routes/users/users.ts

shows storage analytics and refreshes on upload and delete

Storage analytics

---

client/src/components/Drawer.tsx
client/src/components/StorageAnalytics.tsx
client/src/interfaces/File.ts
server/src/db_models/FileModel.ts
server/src/routes/files/files.ts
server/src/routes/users/users.ts

implemented the steps outlined in this [ticket](https://github.com/users/gyuheon0h/projects/2?pane=issue&itemId=98851058&issue=gyuheon0h%7Cdesign-proj%7C130)
**FYI:**
haven't been able to extensively test bc i wasn't able to upload a large file if anyone knows how to/can do it for me... also the progress bar does not refresh on its own so once u successfuly upload, refresh page
also u need to upload brand new files since all _legacy_ files have a `fileSize` of 0

file size tracking

---

client/src/components/Drawer.tsx

collapsable navbar quick fix

---

client/src/components/File.tsx
client/src/components/FileContainer.tsx
client/src/components/MoveDialog.tsx
client/src/components/PermissionsDialog.tsx

can't add screen recording because it's too large but i sent in the chat

more ui changes to move, share

---

client/src/components/CreateFileDialog.tsx
client/src/components/File.tsx
client/src/components/FileContainer.tsx
client/src/components/MoveDialog.tsx
client/src/components/OwlNoteEditorDialog.tsx
client/src/components/OwlNoteViewer.tsx
client/src/components/PermissionsDialog.tsx
client/src/utils/helperRequests.ts

- changed avatar colors
- included "Last Modified by ___"

final UI fixes
